name: "Reusable Deployment Workflow"
on:
  workflow_call:
jobs:
  reusable_workflow_job:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: "Check for deploy comment"
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: deploy
      with:
        trigger: '@deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: "GitHub API Request"
      if: steps.deploy.outputs.triggered == 'true'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Get PR branch info"
      if: steps.deploy.outputs.triggered == 'true'
      id: pr_data
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
        echo "::set-output name=sha::${{ fromJson(steps.request.outputs.data).head.sha }}"
    - name: "Clone the PR branch"
      if: steps.deploy.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ steps.pr_data.outputs.branch }}
        path: src
    - name: "Clone the infrastructure repo"
      if: steps.deploy.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        repository: gscho/reusable-workflow-test
        path: iaac
    - name: Login to DockerHub
      if: steps.deploy.outputs.triggered == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      if: steps.deploy.outputs.triggered == 'true'
      uses: docker/build-push-action@v3
      with:
        context: ./src
        push: true
        tags: gscho/homework-app:${{ steps.pr_data.outputs.sha }}
    - name: "Configure AWS credentials"
      if: steps.deploy.outputs.triggered == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::700273628989:role/test-repo-deploy-role
        role-session-name: testreposession
        aws-region: us-east-1
    - name: "Run deploy.sh"
      id: run-deployment
      if: steps.deploy.outputs.triggered == 'true'
      run: |
        cd iaac
        ./deploy.sh
        URL=$(cat url.txt)
        echo "::set-output name=url::$URL"
      env:
        DOCKER_IMAGE: gscho/homework-app:${{ steps.pr_data.outputs.sha }}
    - name: Comment PR
      if: steps.deploy.outputs.triggered == 'true'
      uses: thollander/actions-comment-pull-request@v1
      with:
        pr_number: ${{ github.event.issue.number }}
        message: "Application deployed: ${{ steps.run-deployment.outputs.url }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
