on:
  workflow_call:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: '@deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: GitHub API Request
      if: steps.check.outputs.triggered == 'true'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get PR informations
      if: steps.check.outputs.triggered == 'true'
      id: pr_data
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
    - name: clone branch of PR
      if: steps.check.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ steps.pr_data.outputs.branch }}
        path: src
    - name: clone infra as code
      if: steps.check.outputs.triggered == 'true'
      with:
        repo: gscho/resuable-workflow-test
        path: iaac
    - name: Configure AWS Credentials
      if: steps.check.outputs.triggered == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::700273628989:role/test-repo-deploy-role
        role-session-name: testreposession
        aws-region: ${{ env.AWS_REGION }}
    - name: upload a file to s3 
      if: steps.check.outputs.triggered == 'true'
      run: |
        echo "Hello world" > "index.html"
        aws s3 cp ./index.html s3://gscho-test-bucket2/
