on:
  workflow_call:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: '@deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: GitHub API Request
      if: steps.check.outputs.triggered == 'true'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get PR informations
      if: steps.check.outputs.triggered == 'true'
      id: pr_data
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
    - name: clone branch of PR
      if: steps.check.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ steps.pr_data.outputs.branch }}
    - run: ls -la
      if: steps.check.outputs.triggered == 'true'
