name: "Reusable Deployment Workflow"
on:
  workflow_call:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: "Check for deploy comment"
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: deploy
      with:
        trigger: '@deploy'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: "GitHub API Request"
      if: steps.deploy.outputs.triggered == 'true'
      id: request
      uses: octokit/request-action@v2.0.0
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Get PR branch name"
      if: steps.deploy.outputs.triggered == 'true'
      id: pr_data
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
    - name: "Clone the PR branch"
      if: steps.deploy.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ steps.pr_data.outputs.branch }}
        path: src
    - name: "Clone the infrastructure repo"
      if: steps.deploy.outputs.triggered == 'true'
      uses: actions/checkout@v3
      with:
        repo: gscho/resuable-workflow-test
        path: iaac
    - name: "Configure AWS credentials"
      if: steps.deploy.outputs.triggered == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::700273628989:role/test-repo-deploy-role
        role-session-name: testreposession
        aws-region: us-east-1
    - name: "Run deploy.sh"
      if: steps.deploy.outputs.triggered == 'true'
      run: |
        cd iaac
        ./deploy.sh
        URL=$(cat url.txt)
        echo '::set-output name=deployment-url::$URL'
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: "Application deployed: ${{ steps.pr_data.outputs.branch }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
